config/routes.rb
Rails.application.routes.draw do
  root to: 'submissions#new'

  get '/index', to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/help' => 'pages#help', as: 'help'
  get '/glbrc_strains' => 'pages#glbrc_strains', as: 'glbrc_strains'
  get '/thousand_genome_strains' => 'pages#thousand_genome_strains', as: 'thousand_genome_strains'
  post '/results/export', to: 'results#export', as: 'checked_result'

  resources :messages, only: %i[new create]
  resources :users, only: %i[index show edit update]
  resources :submissions do
    post :stub_create, on: :member
  end
  resources :genes do
    get :get, on: :collection
  end
  resources :results do
    get :export, on: :collection
  end
  resources :strains, only: %i[index]
  resources :offsite_searches

  get '/status', to: 'api/v1/status#status'
  namespace :api do
    namespace :v1 do
      get '/status', to: 'status#status'
    end
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  has_many :results, dependent: :destroy, class_name: 'Result'
  belongs_to :gene, optional: true
  belongs_to :strain, optional: true
  validates :pam_sequence, :spacer_length, presence: true

  def self.cleanup(run_id)
    Dir.glob("lib/python_scripts/tmp/*-#{run_id}*.txt").each { |file| File.delete(file) }
    Dir.glob("lib/python_scripts/output/*-#{run_id}*.txt").each { |file| File.delete(file) }
    Dir.glob("lib/python_scripts/output/*-#{run_id}*.fa").each { |file| File.delete(file) }
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  after_action :limit_saved_submissions, only: %i[create]
  before_action :set_resource, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token, only: [:create]

  def new
    @submission = Submission.new
    # @offsite_search = OffsiteSearch.new
    # The default set of genes to show for yeast strains.
    @strains = { yeast: Strain.yeast.select(:name, :id), zymo: Strain.zymo.select(:name, :id) }

    # Genes to show if the strain 'GLBRCY22-3' is selected.
    @genes = { yeast: {
      s288c: Gene.where(genome: 'S288C').select(:name, :id).order(:name),
      y22_3: Gene.where(genome: 'Y22-3').select(:name, :id).order(:name)
    },
               zymo: Gene.where(genome: 'ZM4').select(:name, :id).order(:name) }
    @active_tab = params[:active].presence || 'target_gene_yeast'
    @host = APP_CONFIG[:host]
  end

  def show
    @submission = Submission.find(params[:id])
    @results = @submission.results

    if @submission.submission_type == 'custom'
      @locus_start = 1
      @locus_end = @submission.sequence.length
      @chrom_start = 'I'
      @all_strains_count = 1
    else
      @strain = Strain.find(@submission.strain_id)
      @gene = Gene.find(@submission.gene_id)
      @locus_start = @gene.start_pos - 50
      @locus_end = @gene.end_pos + 50
      @chrom_start = @gene.chrom
      @all_strains_count = Strain.where(strain_set: @submission.strain.strain_set).count
    end
    @sgrna_length = @submission.spacer_length
    @pam = @submission.pam_sequence
    @genome = @submission.genome

    if @submission.submission_type == 'custom'
      File.open('public/custom.fasta', 'w+') do |f|
        f << ">I\n"
        f << @submission.sequence.delete(" \t\r\n")
      end
      # have to make .fai index of fasta file for igv to view it
      `samtools faidx public/custom.fasta`
    end

    @chrom_types = %w[yeast zymo]

    File.open('public/generated_sgrna_coords_pos.bed', 'w+') do |f|
      @results.each do |r|
        position = r.pos_in_gene.to_i if @submission.submission_type == 'custom'
        position = r.pos.to_i if @chrom_types.include?(@submission.submission_type)
        chrom = 'I' if @submission.submission_type == 'custom'
        chrom = r.chrom if @chrom_types.include?(@submission.submission_type)
        if r.strand == '+'
          chromend = position + r.sgrna_sequence.length.to_i
          f << "#{chrom}\t#{position}\t#{chromend}\t#{r.name}\n"
        end
      end
    end
    File.open('public/generated_sgrna_coords_neg.bed', 'w+') do |f|
      @results.each do |r|
        position = r.pos_in_gene.to_i if @submission.submission_type == 'custom'
        position = r.pos.to_i if @chrom_types.include?(@submission.submission_type)
        chrom = 'I' if @submission.submission_type == 'custom'
        chrom = r.chrom if @chrom_types.include?(@submission.submission_type)
        if r.strand == '-'
          chromend = position + r.sgrna_sequence.length.to_i
          f << "#{chrom}\t#{position}\t#{chromend}\t#{r.name}\n"
        end
      end
    end
  end

  def create
    @submission = Submission.new(resource_params)
    @submission.created_by = 'Crispy User'

    if @submission.submission_type == 'custom'
      seq = @submission.sequence.gsub(/\s+/, '').upcase
      if /([^ATGC\n])/i.match?(seq)
        redirect_to '/'
        flash[:danger] = 'Target Sequence contains non-DNA characters!'
      elsif @submission.save
        outputfile = "lib/python_scripts/output/crispy-results-000#{@submission.id}.txt"
        params = {
          submission_type: 'custom',
          sequence: seq,
          genome: @submission.genome,
          pam: @submission.pam_sequence,
          spacer: @submission.spacer_length,
          target: 'gene',
          outputfile: outputfile,
          submission_id: @submission.id
        }

        Submission.cleanup('000' + @submission.id.to_s)
        CrispyService.crispy(params)
        render status: :ok, json: { message: 'success', id: @submission.id }.to_json
      else
        render status: :internal_server_error, json: { message: 'Unable to submit run', errors: @submission.errors.to_hash }.to_json
      end
    else # gene submission
      zymo_strain = Strain.find_by(name: 'ZM4')
      strain_name = nil
      @strain_set = nil
      if resource_params[:strain_id].to_i == zymo_strain.id
        strain_name = 'ZYMOMONAS'
      else
        strain = Strain.find(@submission.strain_id)
        strain_name = strain.name
        @strain_set = strain.strain_set
      end

      if @submission.save!

        outputfile = "lib/python_scripts/output/crispy-results-#{@submission.id}.txt"
        blast_output_file = "lib/python_scripts/output/crispy-results-#{@submission.id}_blast.txt"
        params = {
          submission_type: 'gene',
          gene: Gene.find(@submission.gene_id).name,
          pam: @submission.pam_sequence,
          spacer: @submission.spacer_length,
          strain: strain_name,
          strain_set: @strain_set,
          target: 'gene',
          outputfile: outputfile,
          submission_id: @submission.id,
          search_human_genome: @submission.search_human_genome,
          blast_output_file: blast_output_file
        }
        # CrispyStubService.crispy(params)
        CrispyService.crispy(params)
        Submission.cleanup(@submission.id)

        render status: :ok, json: { message: 'success', id: @submission.id }.to_json
      else
        render status: :internal_server_error, json: { message: 'Unable to submit run', errors: @submission.errors.to_hash }.to_json
      end
    end
  end

  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def limit_saved_submissions
    Submission.order('created_at DESC').offset(10).destroy_all
  end

  def set_resource
    @submission = Submission.find(params[:id])
  end

  def resource_params
    params.require(:submission)
          .permit(:submission_type, :sequence, :genome, :gene_id, :strain_id, :pam_sequence,
            :spacer_length, :target_type, :strain_set, :search_human_genome,
            :target_name, :pos_in_gene)
  end
end

app/helpers/submission_helper.rb
module SubmissionHelper
  def count_coverage(cov_string, strain)
    if cov_string.present?
      strain_count = cov_string.squish.split(',').uniq.count
      all_strains_count = Strain.where(strain_set: strain.strain_set).count
      "#{strain_count} / #{all_strains_count}"
    else
      "1 / #{all_strains_count}"
    end
  end

  def coverage_num(cov_string)
    cov_string.squish.split(',').uniq.count
  end
end

app/views/submissions/_form.html.erb
Form Goes Here

app/views/submissions/export_genbank.js.erb
var selecteditems = [];

$("#results").find("input:checked").each(function (i, ob) {
  selecteditems.push($(ob).val());
});
console.log(selecteditems);

let path = '/submissions/' + "<%= @submission.id %>" + '/export_csv.text?selected_ids=' + selecteditems.join(',')
console.log(path);
window.open(path, "_top");

app/views/submissions/new.html.erb
<%= content_for :pagetop do %>

<% end %>
<div class='text-center'>
  <img src='<%= asset_pack_path "media/packs/images/crispy-pop3.svg" %>' height="35%" width="35%" /><br /><br /><br />
  <div class="row">
    <div class="offset-md-1 col-md-10">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= react_component('CrispySubmissionForm', strains: @strains, genes: @genes, host: @host) %>
        </div>
      </div>
    </div>
  </div>

</div>
<br/>
<div class="dna" id="spinner" style="visibility: hidden;">
  <% 60.times do %>
    <div class="ele">
      <div class="dot">
      </div>
    </div>
  <% end%>
</div>

app/views/submissions/show.html.erb
<% content_for :pagetitle do %>
  <%= "Run Submission: #{@submission.id}" %>
  <ul>
    <li>
      <%= "Gene: #{@gene.name}, Strain: #{@strain.name}, Spacer Length: #{@submission.spacer_length}, Strain Set: #{@strain.strain_set}" if @chrom_types.include?(@submission.submission_type) %>
      <%= "Custom Target: #{@submission.target_name}" if @submission.submission_type == 'custom' %>
    </li>
  </ul>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info" id="browse_frame" style="width: 1610px; height: 475px;">
      <div class="panel-heading panel-custom">
        <h3 class="panel-title text-center">Genome Viewer</h3>
      </div>
      <div class="panel-body">
        <% strain_name = @chrom_types.include?(@submission.submission_type) ? @strain.name : 'CUSTOM' %>
        <% target_name = @chrom_types.include?(@submission.submission_type) ? 'gene' : 'CUSTOM' %>
        <%= react_component('SubmissionShow', host: APP_CONFIG[:host], strainName: strain_name, chromStart: @chrom_start, locusStart: @locus_start.to_s, locusEnd: @locus_end.to_s, results: @submission.results, spacerLength: @submission.spacer_length, allStrainsCount: @all_strains_count, pam: @submission.pam_sequence, targetName: target_name) %>
      </div>
    </div>
  </div>
</div>

app/views/submissions/show_custom.html.erb
<% content_for :pagetitle do %>
  <%= "Custom Target Run Submission: #{@custom_submission.id}" %>
  <ul>
    <li>
      <%= "Sequence Target Length: #{@custom_submission.sequence.length},  Spacer Length: #{@custom_submission.spacer_length}" %>
    </li>
    <li>
      <%= "Target Name: #{@custom_submission.target_name}" %>
    </li>
  </ul>
<% end %>

<% content_for :itembar do %>
  <%= link_to 'Back to Custom Target Submission', new_submission_path(active: 'target_custom_seq'), class: 'btn btn-primary' %>
<% end %>
<% if @results.empty? %>
  <h3>
    <%= "No Guide RNA sites found within supplied sequence part of genome reference #{@custom_submission.genome}" %>
  </h3>
<% else %>
  <div class="row">
    <div class="col-md-7">
      <div class="panel panel-info" id="browse_frame" style="width: 1350px; height: 475px;">
        <div class="panel-heading panel-custom">
          <h3 class="panel-title text-center">Genome Viewer</h3>
        </div>
        <div class="panel-body">
          <div id="browser" style="max-height: 400px; overflow-y: scroll;"></div>
          <%= form_tag ((defined? search_path) ? search_path : {}), {method: :get, class: 'form-inline search'} do %>
            <%= hidden_field_tag :direction, params[:direction] %>
            <%= hidden_field_tag :sort, params[:sort] %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

Click on Column headers to sort
<div class="row">
  <div class="col-md-7" id="results" style="width: 1375px;">
    <%= bootstrap_form_tag(url: checked_result_url, method: :post, :html => {:id => "export_form"}) do |f| %>
      <%= hidden_field_tag(:format, 'csv') %>
      <%= hidden_field_tag(:pam, @pam) %>
      <%= hidden_field_tag(:target_name, @custom_submission.target_name) %>
      <div class="pull-right">
        <%= link_to 'Select All', '#', class: 'btn btn-default', id: 'select_all_btn' %>
        <%= f.submit 'Export', id: 'export_btn', data: { disable_with: false }, class: 'btn btn-success' %>
      </div>
      <br/>
      <br/>
      <table class="table" id="results">
        <thead>
          <tr id="head_row" style="background-color: #1E99E8; color: white; border-radius: 10px;">
            <th style="border-radius: 5px 0 0 0px;">Name</th>
            <th>sgRNA Sequence</th>
            <th>PAM Site</th>
            <th>Go To</th>
            <th>
              <%= sortable "perc_activity",  "Percent Activity" %>
            </th>
            <th>
              <%= sortable "gc", "GC%" %>
            </th>
            <% unless @genome == 'None' %>
              <th>
                <%= sortable "chrom", "Chromosome" %>
              </th>
              <th>
                <%= sortable "pos", "Position" %>
              </th>
            <% end %>
            <th>
              <%= sortable "pos_in_gene","Position In Sequence" %>
            </th>
            <th>Strand</th>
            <% unless @genome == 'None' %>
              <th>
                <%= sortable "num_off_site_match", "Off-Site Matches" %>
              </th>
            <% end %>
            <th style="border-radius: 0 5px 0px 0;"></th>
          </tr>
        </thead>
        <tbody>
          <% @results.each do |result| %>
            <tr class="result_row" id="<%= result.name %>">
              <td>
                <%= "#{@custom_submission.target_name}:#{result.name}" %>
              </td>
              <% if result.state == 'Used' %>
                <td style="background-color: MediumSeaGreen; color: white;">
                  <%= result.sgrna_sequence[0...-@pam.length] %>
                </td>
              <% else %>
                <td>
                  <%= result.sgrna_sequence[0...-@pam.length] %>
                </td>
              <% end %>
              <td>
                <%= result.sgrna_sequence.last(@pam.length) %>
              </td>
              <td>
                <button class="btn btn-success" onclick="zoomViewer(<%= result.pos_in_gene %>);">Go</button>
              </td>
              <td>
                <%= result.perc_activity %>
              </td>
              <td>
                <%= result.gc %>
              </td>
              <% unless result.chrom.nil? %>
                <td>
                  <%= result.chrom %>
                </td>
              <% end %>
              <% unless result.pos.nil? %>
                <td>
                  <%= result.pos %>
                </td>
              <% end %>
              <td>
                <%= result.pos_in_gene %>
              </td>
              <td>
                <%= result.strand %>
              </td>
              <% unless @genome == 'None' %>
                <td class="offsite_cnt">
                  <%= result.num_off_site_match %>
                </td>
              <% end %>
              <td>
                <%= check_box_tag 'checked_ids[]', result.id, false %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
<div id="task-form" style="display:none;"></div>
<script>


  $('#select_all_btn').click( function() {
    selectAll();
  });

  var toggleAll = false;

  function selectAll() {
   $('input[name="checked_ids[]"]').each(function(){
      if(toggleAll == true) {
        $(this).prop('checked', false);
      }
      else {
        $(this).prop('checked', true);
      }
   });
   toggleAll = !toggleAll;
  }

  $('#export_btn').click( function () {
    function reload(){
      document.getElementById("export_form").reset();
    };
    window.setTimeout( reload, 10 );

  });

  //highlight instances of offsite hits predicted
  $('.offsite_cnt').each(function() {
    if (parseInt($(this).text()) > 0) {
        $(this).css("background-color","red");
    }
  });

  var div = $("#browser")[0];

  fastaURL = "/custom.fasta";
  genesBed = null;
  geneTrackName = null;

  options = {
        palette: ["#00A0B0", "#6A4A3C", "#CC333F", "#EB6841"],
        locus: "#{@chrom_start}:#{@locus_start}-#{@locus_end}",

        reference: {
            id: "Custom Target",
            fastaURL: fastaURL
        },
        tracks: [
            {
                name: "Generated sgRNAs Forward Strand",
                url: "/generated_sgrna_coords_pos.bed",
                displayMode: "EXPANDED"
            },
            {
                name: "Generated sgRNAs Reverse Strand",
                url: "/generated_sgrna_coords_neg.bed",
                color: "purple",
                displayMode: "EXPANDED"
            }]
          };

  browser = igv.createBrowser(div, options);

  function zoomViewer(position) {
    startCoord = parseInt(position) - 10;
    len = parseInt("#{@sgrna_length}");
    endCoord = parseInt(position) + len + 10;
    locusString = "#{@chrom_start}:" + startCoord + "-" + endCoord;
    igv.browser.search(locusString)
    $("html, body").animate({ scrollTop: 0 }, "medium");
  }

</script>