config/routes.rb
Rails.application.routes.draw do
  root to: 'submissions#new'

  get '/index', to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/help' => 'pages#help', as: 'help'
  get '/glbrc_strains' => 'pages#glbrc_strains', as: 'glbrc_strains'
  get '/thousand_genome_strains' => 'pages#thousand_genome_strains', as: 'thousand_genome_strains'
  post '/results/export', to: 'results#export', as: 'checked_result'

  resources :messages, only: %i[new create]
  resources :users, only: %i[index show edit update]
  resources :submissions do
    post :stub_create, on: :member
  end
  resources :genes do
    get :get, on: :collection
  end
  resources :results do
    get :export, on: :collection
  end
  resources :strains, only: %i[index]
  resources :offsite_searches

  get '/status', to: 'api/v1/status#status'
  namespace :api do
    namespace :v1 do
      get '/status', to: 'status#status'
    end
  end
end

app/views/layouts/_feedback.html.erb
<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#feedback_modal">
  Give Feedback
</button>
<div data-backdrop="false" class="modal fade" id="feedback_modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Message GLBRC Helpdesk</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= bootstrap_form_for(Message.new) do |f| %>
        <div class="modal-body">
          <%= f.text_field :name, label: 'Sender', value: 'CRISpy-pop User' %>
          <%= f.email_field :email, label: 'Contact', value: 'no-reply@glbrc.org' %>
          <%= f.text_area :content, placeholder: 'Your Message', label: 'Message'%>
          <%= f.hidden_field :current_page, value: request.original_url, id: 'help-current-page'%>
        </div>
        <div class="modal-footer">
          <%= f.submit 'Send Message', class: 'btn btn-success', data: {toggle: 'modal', target: '#need-help-modal'} %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="main-footer" role="contentinfo" aria-label="Footer">
  <div class="container">
    <small class='pull-right'>Version: <%= $VERSION %> © Copyright Great Lakes Bioenergy Research Center 2019. All rights reserved.</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class='container-fluid'>
  <div class="navbar-header"><a class="navbar-brand" href="/">
    CRISpy-pop</a>
  </div>
  <div id="header_links" class="collapse navbar-collapse" style="width: 200px;">
    <ul class="navbar-nav mr-auto">
      <li>
        <a href='<%= strains_path %>' style="color: #8d9ba3">
          <i class="fa fa-bug fa-lg fa-fw ml-5" style="color: #8d9ba3"></i>
          Strains
        </a>
      </li>
      <li>
        <a href='about' style="color: #8d9ba3">
          <i class="fa fa-question-circle fa-lg fa-fw ml-3" style="color: #8d9ba3"></i>
          About
        </a>
      </li>
      <li>
        <a href='help' style="color: #8d9ba3">
          <i class="fa fa-ambulance fa-lg fa-fw ml-3" style="color: #8d9ba3"></i>
          Help
        </a>
      </li>
    </ul>
  </div>
  <ul class="nav navbar-right">
    <%= render "layouts/feedback" %>
  </ul>

</div>

app/views/layouts/_menu.html.erb
<div id='sidebar-container' class='sidebar-expanded d-none d-md-block'>
  <ul id="sidebar-list" class='list-group'>
    <li class='list-group-item'>
      Menu Item1
    </li>
    <li class='list-group-item'>
      Menu Item2
    </li>
  </ul>
</div>

app/views/layouts/_messages.html.erb
<div id='messages'>
  <% flash.each do |key, value| %>
    <% if key != 'timedout' %>
      <% next if (value == 'You need to sign in or sign up before continuing.' && key == 'alert' && params['controller'] == 'devise/sessions' && params['action'] == 'new') %>
      <div class="alert alert-<%= key %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value.html_safe %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRISpy-pop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
        <nav class='navbar navbar-expand-lg navbar-dark top-nav-top' role="navigation" style="background-color: #302d2d">
          <%= render 'layouts/header' %>
        </nav>
      <div class="wrapper">
        <div id="page-wrapper" style="min-height: 850px; margin-top: 20px; margin-left: 75px; padding-top: 5px; width: 100%;">

          <div class='container-fluid'>
            <% if content_for?(:pagetitle) || content_for?(:item_bar) %>
              <div class='page-header'>
                <div class='row'>
                  <div class='col-md-6'>
                    <h2><%= yield(:pagetitle) if content_for?(:pagetitle) %></h2>
                  </div>
                  <div class='col-md-6'>
                    <div class='item-bar'><%= yield :item_bar if content_for?(:item_bar) %></div>
                  </div>
                </div>
              </div>
            <% end %>
            <br>
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' if request.fullpath == '/' %>
  </body>
</html>